name: country_picker
description: A flutter package to select a country from a list of countries.

version: 1.1.4
homepage: https://github.com/uyit14
repository: https://github.com/uyit14/flutter_country_picker

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0

flutter: